package army {

  import datatypes._

  sealed abstract class MilitaryUnit(val techLevel: Int, val techGroup: TechGroup, val `type`: UnitType,
                                     val name: String,
                                     val off_fire: Int,
                                     val def_fire: Int,
                                     val off_shock: Int,
                                     val def_shock: Int,
                                     val off_morale: Int,
                                     val def_morale: Int)

  object MilitaryUnit {
    def getUnitType(unitType: UnitType, techGroup: TechGroup, milTechModifier: MilTechModifier): List[MilitaryUnit] = {
      MilitaryUnit.values.filter(unit => unit.`type` == unitType && unit.techGroup == techGroup && unit.techLevel <= milTechModifier.level).toList
    }
    val values = Vector(ADAL_GUERILLA_WARFARE, ADAL_GUNPOWDER_WARFARE,AFRICAN_ABYSSINIAN_CAVALRY, AFRICAN_ABYSSINIAN_LIGHT_CAVALRY, AFRICAN_CLUBMEN, AFRICAN_CUIRASSIER, AFRICAN_DRAGOON, AFRICAN_HILL_WARFARE, AFRICAN_HUSSAR, AFRICAN_MANDELAKU,AFRICAN_MOSSI_HORSEMEN, AFRICAN_SOMALI_CAVALRY, AFRICAN_SPEARMEN, AFRICAN_SWARM, AFRICAN_TUAREG_CAVALRY, AFRICAN_WESTERN_FRANCHISE_WARFARE, AFSHARID_REFORMED, AFSHARID_REFORMED_INFANTRY, ALGONKIN_TOMAHAWK_CHARGE, ANGLOFRENCH_LINE, APACHE_GUERILLA, ASIAN_ARQUEBUSIER, ASIAN_CHARGE_CAVALRY, ASIAN_MASS_INFANTRY, ASIAN_MUSKETEER, AUSTRIAN_GRENZER, AUSTRIAN_HUSSAR, AUSTRIAN_JAEGER, AUSTRIAN_TERCIO, AUSTRIAN_WHITE_COAT, AZTEC_GUNPOWDER_WARFARE, AZTEC_HILL_WARFARE, AZTEC_TRIBAL_WARFARE, BANTU_GUNPOWDER_WARFARE, BANTU_PLAINS_WARFARE, BANTU_TRIBAL_WARFARE, BARDICHE_INFANTRY, BHONSLE_CAVALRY, BHONSLE_INFANTRY, BRITISH_HUSSAR, BRITISH_REDCOAT, BRITISH_SQUARE, CENTRAL_AMERICAN_DRAGOON, CENTRAL_AMERICAN_HORSEMEN, CENTRAL_AMERICAN_HUSSAR, CENTRAL_AMERICAN_RIFLE_CAVALRY, CENTRAL_AMERICAN_SWARM, CHAMBERED_DEMI_CANNON, CHEVAUCHEE, CHINESE_DRAGOON, CHINESE_FOOTSOLDIER, CHINESE_LONGSPEAR, CHINESE_STEPPE, COEHORN_MORTAR, COMMANCHE_SWARM, CREEK_ARQUEBUSIER, CULVERIN, DRUZHINA_CAVALRY, DURRANI_DRAGOON, DURRANI_RIFLED_MUSKETEER, DURRANI_SWIVEL, DUTCH_MAURICIAN, EAST_ASIAN_SPEARMEN, EAST_MONGOLIAN_STEPPE, EASTERN_BOW, EASTERN_CARABINIER, EASTERN_KNIGHTS, EASTERN_MEDIEVAL_INFANTRY, EASTERN_MILITIA, EASTERN_SKIRMISHER, EASTERN_UHLAN, ETHIOPIAN_GUERILLA_WARFARE, ETHIOPIAN_GUNPOWDER_WARFARE, ETHIOPIAN_MOUNTAIN_WARFARE, FLYING_BATTERY, FRENCH_BLUECOAT, FRENCH_CARABINIER, FRENCH_CARACOLLE, FRENCH_CUIRASSIER, FRENCH_DRAGOON, FRENCH_IMPULSE, GAELIC_FREE_SHOOTER, GAELIC_GALLOGLAIGH, GAELIC_MERCENARY, GERMANIZED_PIKE, HALBERD_INFANTRY, HAN_BANNER, HOUFNICE, HUNGARIAN_HUSSAR, HURON_ARQUEBUSIER, INCA_MOUNTAIN_WARFARE, INCAN_AXEMEN, INCAN_GUERILLA_WARFARE, INCAN_SLINGSHOTS, INDIAN_ARCHERS, INDIAN_ARQUEBUSIER, INDIAN_ELEPHANT, INDIAN_FOOTSOLDIER, INDIAN_RIFLE, INDIAN_SHOCK_CAVALRY, IRISH_CHARGE, IROQUOIS_RIFLE_SCOUT, ITALIAN_CONDOTTA, JAPANESE_ARCHER, JAPANESE_FOOTSOLDIER, JAPANESE_SAMURAI, LARGE_CAST_BRONZE_MORTAR, LARGE_CAST_IRON_BOMBARD, LEATHER_CANNON, MAHARATHAN_CAVALRY, MAHARATHAN_GUERILLA_WARFARE, MALI_TRIBAL_WARFARE, MAMLUK_ARCHER, MAMLUK_CAVALRY_CHARGE, MAMLUK_DUEL, MAMLUK_MUSKET_CHARGE, MANCHU_BANNER, MAYA_FOREST_WARFARE, MAYA_GUERILLA_WARFARE, MAYA_GUNPOWDER_WARFARE, MAYA_TRIBAL_WARFARE, MESOAMERICAN_SPEARMEN, MEXICAN_GUERILLA_WARFARE, MIXED_ORDER_INFANTRY, MONGOL_BOW, MONGOL_STEPPE, MONGOL_SWARM, MONGOLIAN_BOW, MUGHAL_MANSABDAR, MUGHAL_MUSKETEER, MUSCOVITE_CARACOLLE, MUSCOVITE_COSSACK, MUSCOVITE_MUSKETEER, MUSCOVITE_SOLDATY, MUSLIM_CAVALRY_ARCHERS, MUSLIM_DRAGOON, MUSLIM_MASS_INFANTRY, NAPOLEONIC_LANCERS, NAPOLEONIC_SQUARE, NATIVE_CLUBMEN, NATIVE_INDIAN_ARCHER, NATIVE_INDIAN_HORSEMEN, NATIVE_INDIAN_MOUNTAIN_WARFARE, NATIVE_INDIAN_TRIBAL_WARFARE, NIGER_KONGOLESE_FOREST_WARFARE, NIGER_KONGOLESE_GUERILLA_WARFARE, NIGER_KONGOLESE_GUNPOWDER_WARFARE, NIGER_KONGOLESE_TRIBAL_WARFARE, NORTH_AMERICAN_HUSSAR, NORTH_AMERICAN_RIFLE_CAVALRY, OPEN_ORDER_CAVALRY, OTTOMAN_AZAB, OTTOMAN_JANISSARY, OTTOMAN_LANCER, OTTOMAN_MUSELLEM, OTTOMAN_NEW_MODEL, OTTOMAN_NIZAMI_CEDID, OTTOMAN_REFORMED_JANISSARY, OTTOMAN_REFORMED_SPAHI, OTTOMAN_SEKBAN, OTTOMAN_SPAHI, OTTOMAN_TIMARIOT, OTTOMAN_TOPRAKLI_DRAGOON, OTTOMAN_TOPRAKLI_HIT_AND_RUN, OTTOMAN_YAYA, PEDRERO, PERSIAN_CAVALRY_CHARGE, PERSIAN_FOOTSOLDIER, PERSIAN_RIFLE, PERSIAN_SHAMSHIR, PERUVIAN_GUERILLA_WARFARE, POLISH_HUSSAR, POLISH_MUSKETEER, POLISH_TERCIO, POLISH_WINGED_HUSSAR, PRUSSIAN_DRILL, PRUSSIAN_FREDERICKIAN, PRUSSIAN_UHLAN, PUEBLO_AMBUSH, QIZILBASH_CAVALRY, RAJPUT_HILL_FIGHTERS, RAJPUT_MUSKETEER, REFORMED_ASIAN_CAVALRY, REFORMED_ASIAN_MUSKETEER, REFORMED_MANCHU_RIFLE, REFORMED_MUGHAL_MANSABDAR, REFORMED_MUGHAL_MUSKETEER, REFORMED_STEPPE_RIFLES, REFORMED_WESTERNIZED_INCAN, ROYAL_MORTAR, RUSSIAN_COSSACK, RUSSIAN_CUIRASSIER, RUSSIAN_GREEN_COAT, RUSSIAN_LANCER, RUSSIAN_MASS, RUSSIAN_PETRINE, SAXON_INFANTRY, SCHWARZE_REITER, SCOTTISH_HIGHLANDER, SHAYBANI, SIKH_HIT_AND_RUN, SIKH_RIFLE, SIOUX_DRAGOON, SLAVIC_STRADIOTI, SMALL_CAST_IRON_BOMBARD, SONGHAI_TRIBAL_WARFARE, SOUTH_AMERICAN_ARQUEBUSIER, SOUTH_AMERICAN_DRAGOON, SOUTH_AMERICAN_FOREST_WARFARE, SOUTH_AMERICAN_GUNPOWDER_WARFARE, SOUTH_AMERICAN_HORSEMEN, SOUTH_AMERICAN_HUSSAR, SOUTH_AMERICAN_REFORMED_GUNPOWDER_WARFARE, SOUTH_AMERICAN_RIFLE_CAVALRY, SOUTH_AMERICAN_SPEARMEN, SOUTH_AMERICAN_SWARM, SOUTH_AMERICAN_WARFARE, SOUTH_INDIAN_MUSKETEER, SPANISH_TERCIO, STEPPE_CAVALRY, STEPPE_FOOTMEN, STEPPE_INFANTRY, STEPPE_LANCERS, STEPPE_MOUNTED_RAIDERS, STEPPE_MUSKETEERS, STEPPE_RAIDERS, STEPPE_RIDERS, STEPPE_RIFLES, STEPPE_UHLANS, SWEDISH_ARME_BLANCHE, SWEDISH_CAROLINE, SWEDISH_GALLOP, SWEDISH_GUSTAVIAN, SWISS_LANDSKNECHTEN, SWIVEL_CANNON, TARTAR_COSSACK, TIPU_SULTAN_ROCKET, TOFONGCHIS_MUSKETEER, TOPCHIS_ARTILLERY, WESTERN_LONGBOW, WESTERN_MEDIEVAL_INFANTRY, WESTERN_MEDIEVAL_KNIGHTS, WESTERN_MEN_AT_ARMS, WESTERNIZED_ADAL, WESTERNIZED_AZTEC, WESTERNIZED_BANTU, WESTERNIZED_ETHIOPIAN, WESTERNIZED_INCAN, WESTERNIZED_MAYAN, WESTERNIZED_NIGER_KONGOLESE, WESTERNIZED_SOUTH_AMERICAN, WESTERNIZED_ZAPOTEC, ZAPOROGHIAN_COSSACK, ZAPOTEC_GUNPOWDER_WARFARE, ZAPOTEC_PLAINS_WARFARE, ZAPOTEC_TRIBAL_WARFARE)
  }

  case object ADAL_GUERILLA_WARFARE extends MilitaryUnit(23, SUB_SAHARAN, INFANTRY, "East African Guerrillas", 3, 3, 2, 2, 2, 3)
  case object ADAL_GUNPOWDER_WARFARE extends MilitaryUnit(15, SUB_SAHARAN, INFANTRY, "East African Musketeers", 2, 2, 2, 2, 2, 3)
  case object AFRICAN_ABYSSINIAN_CAVALRY extends MilitaryUnit(10, SUB_SAHARAN, CAVALRY, "Abyssinian Barded Cavalry", 0, 0, 3, 2, 3, 2)
  case object AFRICAN_ABYSSINIAN_LIGHT_CAVALRY extends MilitaryUnit(1, SUB_SAHARAN, CAVALRY, "Abyssinian Light Cavalry", 0, 0, 1, 1, 2, 0)
  case object AFRICAN_CLUBMEN extends MilitaryUnit(1, SUB_SAHARAN, INFANTRY, "African Clubmen", 0, 0, 1, 0, 1, 1)
  case object AFRICAN_CUIRASSIER extends MilitaryUnit(28, SUB_SAHARAN, CAVALRY, "African Cuirassier", 1, 1, 4, 4, 4, 4)
  case object AFRICAN_DRAGOON extends MilitaryUnit(23, SUB_SAHARAN, CAVALRY, "African Dragoon", 1, 1, 3, 3, 4, 4)
  case object AFRICAN_HILL_WARFARE extends MilitaryUnit(12, SUB_SAHARAN, INFANTRY, "African Hill Warriors", 2, 1, 1, 2, 2, 2)
  case object AFRICAN_HUSSAR extends MilitaryUnit(14, SUB_SAHARAN, CAVALRY, "African Hussar", 1, 0, 3, 2, 3, 3)
  case object AFRICAN_MANDELAKU extends MilitaryUnit(1, SUB_SAHARAN, CAVALRY, "Mandekalu Cavalry", 0, 0, 1, 1, 1, 1)
  case object AFRICAN_MOSSI_HORSEMEN extends MilitaryUnit(10, SUB_SAHARAN, CAVALRY, "Mossi Horsemen", 0, 0, 2, 2, 3, 3)
  case object AFRICAN_SOMALI_CAVALRY extends MilitaryUnit(6, SUB_SAHARAN, CAVALRY, "Somali Light Cavalry", 0, 0, 2, 1, 1, 2)
  case object AFRICAN_SPEARMEN extends MilitaryUnit(1, SUB_SAHARAN, INFANTRY, "African Spearmen", 0, 0, 0, 1, 1, 1)
  case object AFRICAN_SWARM extends MilitaryUnit(17, SUB_SAHARAN, CAVALRY, "African Swarm Cavalry", 0, 1, 4, 3, 3, 2)
  case object AFRICAN_TUAREG_CAVALRY extends MilitaryUnit(6, SUB_SAHARAN, CAVALRY, "Tuareg Cavalry", 0, 0, 2, 1, 2, 1)
  case object AFRICAN_WESTERN_FRANCHISE_WARFARE extends MilitaryUnit(30, SUB_SAHARAN, INFANTRY, "African Western Franchise Infantry", 3, 3, 3, 3, 4, 4)
  case object AFSHARID_REFORMED extends MilitaryUnit(18, MUSLIM, CAVALRY, "Afsharid Reformed Cavalry", 0, 1, 4, 3, 3, 3)
  case object AFSHARID_REFORMED_INFANTRY extends MilitaryUnit(15, MUSLIM, INFANTRY, "Afsharid Reformed Infantry", 3, 2, 2, 2, 2, 2)
  case object ALGONKIN_TOMAHAWK_CHARGE extends MilitaryUnit(5, NORTH_AMERICAN, INFANTRY, "Algonkin Tomahawk Warriors", 0, 0, 2, 1, 2, 1)
  case object ANGLOFRENCH_LINE extends MilitaryUnit(23, WESTERN, INFANTRY, "Line Infantry", 3, 3, 2, 2, 3, 3)
  case object APACHE_GUERILLA extends MilitaryUnit(26, NORTH_AMERICAN, INFANTRY, "North American Guerrillas", 4, 3, 2, 4, 3, 3)
  case object ASIAN_ARQUEBUSIER extends MilitaryUnit(9, CHINESE, INFANTRY, "Asian Arquebusier", 1, 1, 1, 1, 1, 1)
  case object ASIAN_CHARGE_CAVALRY extends MilitaryUnit(14, CHINESE, CAVALRY, "Asian Charge Cavalry", 0, 1, 3, 2, 3, 3)
  case object ASIAN_MASS_INFANTRY extends MilitaryUnit(15, CHINESE, INFANTRY, "Asian Mass Infantry", 3, 2, 2, 2, 2, 2)
  case object ASIAN_MUSKETEER extends MilitaryUnit(19, CHINESE, INFANTRY, "Asian Musketeer", 3, 3, 2, 2, 3, 2)
  case object AUSTRIAN_GRENZER extends MilitaryUnit(23, WESTERN, INFANTRY, "Grenzer Infantry", 2, 3, 2, 3, 3, 3)
  case object AUSTRIAN_HUSSAR extends MilitaryUnit(23, WESTERN, CAVALRY, "Latin Hussars", 1, 2, 4, 3, 4, 4)
  case object AUSTRIAN_JAEGER extends MilitaryUnit(30, WESTERN, INFANTRY, "Jaeger Infantry", 4, 4, 4, 3, 3, 4)
  case object AUSTRIAN_TERCIO extends MilitaryUnit(19, WESTERN, INFANTRY, "Reformed Tercio", 2, 2, 2, 3, 3, 3)
  case object AUSTRIAN_WHITE_COAT extends MilitaryUnit(26, WESTERN, INFANTRY, "White Coat Infantry", 4, 3, 3, 3, 3, 4)
  case object AZTEC_GUNPOWDER_WARFARE extends MilitaryUnit(14, MESOAMERICAN, INFANTRY, "American Hill Musketeers", 2, 1, 3, 2, 2, 2)
  case object AZTEC_HILL_WARFARE extends MilitaryUnit(10, MESOAMERICAN, INFANTRY, "Reformed American Hill Warriors", 0, 0, 3, 1, 2, 2)
  case object AZTEC_TRIBAL_WARFARE extends MilitaryUnit(5, MESOAMERICAN, INFANTRY, "American Hill Warriors", 0, 0, 2, 1, 2, 1)
  case object BANTU_GUNPOWDER_WARFARE extends MilitaryUnit(15, SUB_SAHARAN, INFANTRY, "South African Musketeers", 3, 2, 3, 2, 2, 1)
  case object BANTU_PLAINS_WARFARE extends MilitaryUnit(12, SUB_SAHARAN, INFANTRY, "African Plains Warriors", 2, 1, 2, 2, 2, 1)
  case object BANTU_TRIBAL_WARFARE extends MilitaryUnit(5, SUB_SAHARAN, INFANTRY, "South African Warrior", 0, 0, 2, 1, 2, 1)
  case object BARDICHE_INFANTRY extends MilitaryUnit(1, EASTERN, INFANTRY, "Bardiche Infantry", 0, 0, 0, 0, 1, 1)
  case object BHONSLE_CAVALRY extends MilitaryUnit(28, INDIAN, CAVALRY, "Sowars", 1, 2, 4, 4, 4, 3)
  case object BHONSLE_INFANTRY extends MilitaryUnit(18, INDIAN, INFANTRY, "Deccani Musket Infantry", 3, 3, 2, 2, 2, 2)
  case object BRITISH_HUSSAR extends MilitaryUnit(26, WESTERN, CAVALRY, "Reformed Latin Hussars", 1, 2, 4, 4, 4, 4)
  case object BRITISH_REDCOAT extends MilitaryUnit(26, WESTERN, INFANTRY, "Redcoat Infantry", 3, 4, 3, 3, 4, 3)
  case object BRITISH_SQUARE extends MilitaryUnit(28, WESTERN, INFANTRY, "Square Infantry", 3, 4, 3, 3, 4, 4)
  case object CENTRAL_AMERICAN_DRAGOON extends MilitaryUnit(23, MESOAMERICAN, CAVALRY, "Central American Dragoon", 2, 2, 3, 3, 4, 4)
  case object CENTRAL_AMERICAN_HORSEMEN extends MilitaryUnit(6, MESOAMERICAN, CAVALRY, "Central American Horsemen", 0, 0, 2, 1, 1, 1)
  case object CENTRAL_AMERICAN_HUSSAR extends MilitaryUnit(14, MESOAMERICAN, CAVALRY, "Central American Hussar", 1, 1, 3, 2, 3, 2)
  case object CENTRAL_AMERICAN_RIFLE_CAVALRY extends MilitaryUnit(10, MESOAMERICAN, CAVALRY, "Central American Cavalry", 0, 1, 3, 2, 2, 2)
  case object CENTRAL_AMERICAN_SWARM extends MilitaryUnit(19, MESOAMERICAN, CAVALRY, "Central American Swarm Cavalry", 1, 2, 3, 3, 3, 2)
  case object CHAMBERED_DEMI_CANNON extends MilitaryUnit(16, WESTERN, ARTILLERY, "Chambered Demi-Cannon", 2, 2, 0, 1, 2, 1)
  case object CHEVAUCHEE extends MilitaryUnit(1, WESTERN, CAVALRY, "Chevauchée", 0, 0, 1, 1, 1, 0)
  case object CHINESE_DRAGOON extends MilitaryUnit(23, CHINESE, CAVALRY, "Asian Dragoons", 1, 2, 3, 3, 4, 3)
  case object CHINESE_FOOTSOLDIER extends MilitaryUnit(5, CHINESE, INFANTRY, "Offensive Asian Foot Soldier", 0, 0, 1, 0, 2, 1)
  case object CHINESE_LONGSPEAR extends MilitaryUnit(1, CHINESE, INFANTRY, "Asian Longspear Infantry", 0, 0, 0, 1, 0, 1)
  case object CHINESE_STEPPE extends MilitaryUnit(6, CHINESE, CAVALRY, "Asian Steppe Cavalry", 0, 0, 2, 2, 1, 1)
  case object COEHORN_MORTAR extends MilitaryUnit(22, WESTERN, ARTILLERY, "Coehorn Mortar", 3, 3, 1, 1, 3, 3)
  case object COMMANCHE_SWARM extends MilitaryUnit(19, NORTH_AMERICAN, CAVALRY, "North American Swarm Cavalry", 1, 2, 3, 3, 3, 2)
  case object CREEK_ARQUEBUSIER extends MilitaryUnit(14, NORTH_AMERICAN, INFANTRY, "Creek Arquebusier", 2, 2, 2, 2, 2, 2)
  case object CULVERIN extends MilitaryUnit(10, WESTERN, ARTILLERY, "Culverin", 1, 1, 0, 1, 1, 0)
  case object DRUZHINA_CAVALRY extends MilitaryUnit(1, EASTERN, CAVALRY, "Druzhina Cavalry", 0, 0, 0, 1, 1, 1)
  case object DURRANI_DRAGOON extends MilitaryUnit(28, MUSLIM, CAVALRY, "Durrani Cavalry", 2, 1, 5, 3, 4, 4)
  case object DURRANI_RIFLED_MUSKETEER extends MilitaryUnit(23, MUSLIM, INFANTRY, "Reformed Muslim Musketeers", 1, 2, 3, 3, 4, 3)
  case object DURRANI_SWIVEL extends MilitaryUnit(28, MUSLIM, CAVALRY, "Durrani Swivel Cavalry", 1, 2, 4, 5, 4, 3)
  case object DUTCH_MAURICIAN extends MilitaryUnit(15, WESTERN, INFANTRY, "Maurician Infantry", 2, 2, 2, 1, 3, 2)
  case object EAST_ASIAN_SPEARMEN extends MilitaryUnit(1, CHINESE, INFANTRY, "East Asian Spearmen", 0, 0, 0, 1, 1, 0)
  case object EAST_MONGOLIAN_STEPPE extends MilitaryUnit(10, CHINESE, CAVALRY, "Reformed Asian Steppe Cavalry", 1, 0, 2, 2, 2, 2)
  case object EASTERN_BOW extends MilitaryUnit(1, CHINESE, CAVALRY, "East Asian Archer Cavalry", 0, 0, 1, 0, 1, 1)
  case object EASTERN_CARABINIER extends MilitaryUnit(26, OTTOMAN, INFANTRY, "Eastern Carabinier", 4, 3, 3, 3, 3, 3)
  case object EASTERN_KNIGHTS extends MilitaryUnit(1, EASTERN, CAVALRY, "Eastern Knights", 0, 0, 1, 0, 1, 1)
  case object EASTERN_MEDIEVAL_INFANTRY extends MilitaryUnit(1, EASTERN, INFANTRY, "Eastern Medieval Infantry", 0, 0, 1, 0, 1, 0)
  case object EASTERN_MILITIA extends MilitaryUnit(5, EASTERN, INFANTRY, "Eastern Militia", 0, 0, 1, 1, 1, 1)
  case object EASTERN_SKIRMISHER extends MilitaryUnit(26, OTTOMAN, CAVALRY, "Eastern Skirmisher", 1, 2, 4, 3, 4, 3)
  case object EASTERN_UHLAN extends MilitaryUnit(26, OTTOMAN, CAVALRY, "Eastern Uhlan", 2, 1, 3, 4, 4, 3)
  case object ETHIOPIAN_GUERILLA_WARFARE extends MilitaryUnit(23, SUB_SAHARAN, INFANTRY, "North African Guerrillas", 2, 3, 2, 3, 2, 3)
  case object ETHIOPIAN_GUNPOWDER_WARFARE extends MilitaryUnit(15, SUB_SAHARAN, INFANTRY, "North African Musketeers", 2, 3, 2, 3, 1, 2)
  case object ETHIOPIAN_MOUNTAIN_WARFARE extends MilitaryUnit(12, SUB_SAHARAN, INFANTRY, "African Mountain Warriors", 1, 2, 2, 2, 1, 2)
  case object FLYING_BATTERY extends MilitaryUnit(29, WESTERN, ARTILLERY, "Flying Battery", 4, 4, 2, 2, 4, 4)
  case object FRENCH_BLUECOAT extends MilitaryUnit(26, WESTERN, INFANTRY, "Blue Coat Infantry", 3, 3, 3, 3, 4, 4)
  case object FRENCH_CARABINIER extends MilitaryUnit(26, WESTERN, CAVALRY, "Carabiniers", 2, 1, 5, 4, 3, 4)
  case object FRENCH_CARACOLLE extends MilitaryUnit(14, WESTERN, CAVALRY, "Latin Caracole Cavalry", 1, 0, 3, 2, 2, 2)
  case object FRENCH_CUIRASSIER extends MilitaryUnit(28, WESTERN, CAVALRY, "Latin Cuirassiers", 1, 2, 5, 4, 4, 5)
  case object FRENCH_DRAGOON extends MilitaryUnit(23, WESTERN, CAVALRY, "Latin Dragoons", 1, 1, 4, 4, 4, 4)
  case object FRENCH_IMPULSE extends MilitaryUnit(28, WESTERN, INFANTRY, "Impulse Infantry", 4, 3, 3, 3, 4, 4)
  case object GAELIC_FREE_SHOOTER extends MilitaryUnit(12, WESTERN, INFANTRY, "Free Shooter Infantry", 1, 2, 2, 1, 3, 1)
  case object GAELIC_GALLOGLAIGH extends MilitaryUnit(5, WESTERN, INFANTRY, "Galloglaigh Infantry", 0, 0, 1, 0, 2, 0)
  case object GAELIC_MERCENARY extends MilitaryUnit(9, WESTERN, INFANTRY, "Reformed Galloglaigh Infantry", 0, 0, 2, 0, 2, 1)
  case object GERMANIZED_PIKE extends MilitaryUnit(9, EASTERN, INFANTRY, "Pike Infantry", 0, 0, 1, 2, 1, 2)
  case object HALBERD_INFANTRY extends MilitaryUnit(1, WESTERN, INFANTRY, "Halberd Infantry", 0, 0, 1, 0, 1, 0)
  case object HAN_BANNER extends MilitaryUnit(12, CHINESE, INFANTRY, "Banner Infantry", 1, 2, 2, 1, 2, 2)
  case object HOUFNICE extends MilitaryUnit(7, WESTERN, ARTILLERY, "Houfnice", 1, 0, 0, 0, 0, 1)
  case object HUNGARIAN_HUSSAR extends MilitaryUnit(10, EASTERN, CAVALRY, "Eastern Hussar", 0, 0, 2, 2, 3, 2)
  case object HURON_ARQUEBUSIER extends MilitaryUnit(14, NORTH_AMERICAN, INFANTRY, "Native American Arquebusier", 2, 2, 2, 1, 3, 2)
  case object INCA_MOUNTAIN_WARFARE extends MilitaryUnit(5, SOUTH_AMERICAN, INFANTRY, "Reformed Mountain Warriors", 0, 0, 1, 2, 1, 2)
  case object INCAN_AXEMEN extends MilitaryUnit(5, SOUTH_AMERICAN, INFANTRY, "Incan Axemen", 0, 0, 1, 1, 2, 2)
  case object INCAN_GUERILLA_WARFARE extends MilitaryUnit(19, SOUTH_AMERICAN, INFANTRY, "Incan Guerrilla", 2, 3, 2, 2, 2, 3)
  case object INCAN_SLINGSHOTS extends MilitaryUnit(5, SOUTH_AMERICAN, INFANTRY, "Incan Slingshots", 0, 0, 2, 2, 1, 1)
  case object INDIAN_ARCHERS extends MilitaryUnit(1, INDIAN, CAVALRY, "Elephant Archers", 0, 0, 1, 0, 1, 1)
  case object INDIAN_ARQUEBUSIER extends MilitaryUnit(5, INDIAN, INFANTRY, "Indian Arquebusier", 1, 0, 1, 1, 1, 0)
  case object INDIAN_ELEPHANT extends MilitaryUnit(10, INDIAN, CAVALRY, "Mansabdar Cavalry", 1, 0, 3, 2, 2, 2)
  case object INDIAN_FOOTSOLDIER extends MilitaryUnit(1, INDIAN, INFANTRY, "Indian Foot Soldier", 0, 0, 1, 0, 1, 1)
  case object INDIAN_RIFLE extends MilitaryUnit(26, INDIAN, INFANTRY, "North Indian Sepoy", 3, 3, 3, 3, 3, 4)
  case object INDIAN_SHOCK_CAVALRY extends MilitaryUnit(23, INDIAN, CAVALRY, "Deccani Light Cavalry", 1, 1, 4, 3, 4, 3)
  case object IRISH_CHARGE extends MilitaryUnit(15, WESTERN, INFANTRY, "Charge Infantry", 1, 2, 3, 1, 3, 2)
  case object IROQUOIS_RIFLE_SCOUT extends MilitaryUnit(19, NORTH_AMERICAN, INFANTRY, "Rifle Scout Infantry", 3, 3, 2, 2, 2, 2)
  case object ITALIAN_CONDOTTA extends MilitaryUnit(9, WESTERN, INFANTRY, "Condotta Infantry", 0, 0, 2, 1, 1, 1)
  case object JAPANESE_ARCHER extends MilitaryUnit(1, CHINESE, INFANTRY, "Asian Longbow", 0, 0, 1, 0, 0, 1)
  case object JAPANESE_FOOTSOLDIER extends MilitaryUnit(5, CHINESE, INFANTRY, "Defensive Asian Foot Soldier", 0, 0, 1, 1, 1, 1)
  case object JAPANESE_SAMURAI extends MilitaryUnit(6, CHINESE, CAVALRY, "Samurai Cavalry", 0, 0, 2, 1, 2, 1)
  case object LARGE_CAST_BRONZE_MORTAR extends MilitaryUnit(7, WESTERN, ARTILLERY, "Large Cast Bronze Mortar", 1, 0, 0, 0, 1, 0)
  case object LARGE_CAST_IRON_BOMBARD extends MilitaryUnit(13, WESTERN, ARTILLERY, "Large Cast Iron Cannon", 2, 1, 0, 0, 1, 2)
  case object LEATHER_CANNON extends MilitaryUnit(18, WESTERN, ARTILLERY, "Leather Cannon", 2, 2, 1, 1, 2, 2)
  case object MAHARATHAN_CAVALRY extends MilitaryUnit(17, INDIAN, CAVALRY, "Maratha Raiders", 0, 2, 4, 3, 3, 2)
  case object MAHARATHAN_GUERILLA_WARFARE extends MilitaryUnit(23, INDIAN, INFANTRY, "Telingas", 4, 3, 2, 2, 2, 3)
  case object MALI_TRIBAL_WARFARE extends MilitaryUnit(5, SUB_SAHARAN, INFANTRY, "North African Warrior", 0, 0, 2, 2, 1, 1)
  case object MAMLUK_ARCHER extends MilitaryUnit(1, MUSLIM, INFANTRY, "Muslim Archer", 0, 0, 1, 1, 0, 1)
  case object MAMLUK_CAVALRY_CHARGE extends MilitaryUnit(1, MUSLIM, CAVALRY, "Charge Cavalry", 0, 0, 2, 0, 1, 1)
  case object MAMLUK_DUEL extends MilitaryUnit(5, MUSLIM, INFANTRY, "Muslim Duel Infantry", 0, 0, 1, 1, 1, 1)
  case object MAMLUK_MUSKET_CHARGE extends MilitaryUnit(18, MUSLIM, CAVALRY, "Musket Charge Cavalry", 1, 1, 4, 3, 3, 2)
  case object MANCHU_BANNER extends MilitaryUnit(17, CHINESE, CAVALRY, "Banner Cavalry", 1, 1, 3, 3, 3, 3)
  case object MAYA_FOREST_WARFARE extends MilitaryUnit(10, MESOAMERICAN, INFANTRY, "Reformed American Forest Warriors", 0, 0, 2, 2, 2, 2)
  case object MAYA_GUERILLA_WARFARE extends MilitaryUnit(19, MESOAMERICAN, INFANTRY, "American Guerrilla Warfare", 3, 2, 3, 2, 2, 2)
  case object MAYA_GUNPOWDER_WARFARE extends MilitaryUnit(14, MESOAMERICAN, INFANTRY, "American Forest Musketeers", 2, 2, 2, 2, 2, 2)
  case object MAYA_TRIBAL_WARFARE extends MilitaryUnit(5, MESOAMERICAN, INFANTRY, "American Forest Warriors", 0, 0, 2, 1, 1, 2)
  case object MESOAMERICAN_SPEARMEN extends MilitaryUnit(1, MESOAMERICAN, INFANTRY, "Mesoamerican Spearmen", 0, 0, 1, 0, 1, 1)
  case object MEXICAN_GUERILLA_WARFARE extends MilitaryUnit(19, MESOAMERICAN, INFANTRY, "Central American Guerrillas", 2, 2, 2, 2, 3, 3)
  case object MIXED_ORDER_INFANTRY extends MilitaryUnit(30, WESTERN, INFANTRY, "Mixed Order Infantry", 4, 3, 4, 3, 4, 4)
  case object MONGOL_BOW extends MilitaryUnit(1, NOMAD, INFANTRY, "Eastern Archers", 0, 0, 1, 1, 1, 1)
  case object MONGOL_STEPPE extends MilitaryUnit(1, NOMAD, CAVALRY, "Eastern Steppe Cavalry", 0, 0, 1, 1, 2, 2)
  case object MONGOL_SWARM extends MilitaryUnit(1, NOMAD, CAVALRY, "Eastern Swarm Cavalry", 0, 0, 2, 1, 2, 1)
  case object MONGOLIAN_BOW extends MilitaryUnit(1, CHINESE, CAVALRY, "Archer Cavalry", 0, 0, 0, 1, 1, 1)
  case object MUGHAL_MANSABDAR extends MilitaryUnit(6, INDIAN, CAVALRY, "Indian Cavalry Archers", 0, 0, 2, 2, 1, 1)
  case object MUGHAL_MUSKETEER extends MilitaryUnit(9, INDIAN, INFANTRY, "Toofangchis", 1, 1, 1, 1, 2, 1)
  case object MUSCOVITE_CARACOLLE extends MilitaryUnit(14, EASTERN, CAVALRY, "Eastern Caracole", 2, 0, 2, 2, 3, 3)
  case object MUSCOVITE_COSSACK extends MilitaryUnit(22, EASTERN, CAVALRY, "Cossack Cavalry", 1, 1, 4, 3, 4, 4)
  case object MUSCOVITE_MUSKETEER extends MilitaryUnit(12, EASTERN, INFANTRY, "Offensive Eastern Musketeers", 2, 1, 2, 1, 3, 2)
  case object MUSCOVITE_SOLDATY extends MilitaryUnit(15, EASTERN, INFANTRY, "Soldaty Infantry", 3, 1, 2, 1, 3, 2)
  case object MUSLIM_CAVALRY_ARCHERS extends MilitaryUnit(1, MUSLIM, CAVALRY, "Muslim Cavalry Archers", 0, 0, 1, 1, 1, 1)
  case object MUSLIM_DRAGOON extends MilitaryUnit(23, MUSLIM, CAVALRY, "Muslim Dragoon", 1, 2, 3, 4, 3, 4)
  case object MUSLIM_MASS_INFANTRY extends MilitaryUnit(26, MUSLIM, INFANTRY, "Muslim Mass Infantry", 3, 4, 3, 3, 3, 3)
  case object NAPOLEONIC_LANCERS extends MilitaryUnit(28, WESTERN, CAVALRY, "Latin Lancers", 0, 2, 6, 4, 5, 4)
  case object NAPOLEONIC_SQUARE extends MilitaryUnit(30, WESTERN, INFANTRY, "Napoleonic Square", 4, 4, 4, 3, 4, 3)
  case object NATIVE_CLUBMEN extends MilitaryUnit(1, NORTH_AMERICAN, INFANTRY, "Clubmen", 0, 0, 1, 0, 1, 1)
  case object NATIVE_INDIAN_ARCHER extends MilitaryUnit(1, NORTH_AMERICAN, INFANTRY, "Native American Archer", 0, 0, 0, 1, 1, 1)
  case object NATIVE_INDIAN_HORSEMEN extends MilitaryUnit(6, NORTH_AMERICAN, CAVALRY, "North American Horsemen", 0, 0, 2, 1, 1, 1)
  case object NATIVE_INDIAN_MOUNTAIN_WARFARE extends MilitaryUnit(10, NORTH_AMERICAN, INFANTRY, "Native American Mountain Warriors", 1, 1, 1, 2, 2, 1)
  case object NATIVE_INDIAN_TRIBAL_WARFARE extends MilitaryUnit(5, NORTH_AMERICAN, INFANTRY, "American Plains Warriors", 0, 0, 2, 1, 1, 2)
  case object NIGER_KONGOLESE_FOREST_WARFARE extends MilitaryUnit(12, SUB_SAHARAN, INFANTRY, "African Forest Warriors", 1, 1, 2, 2, 2, 2)
  case object NIGER_KONGOLESE_GUERILLA_WARFARE extends MilitaryUnit(23, SUB_SAHARAN, INFANTRY, "Central African Guerrillas", 3, 2, 2, 3, 3, 2)
  case object NIGER_KONGOLESE_GUNPOWDER_WARFARE extends MilitaryUnit(15, SUB_SAHARAN, INFANTRY, "Central African Musketeers", 3, 2, 2, 2, 2, 2)
  case object NIGER_KONGOLESE_TRIBAL_WARFARE extends MilitaryUnit(5, SUB_SAHARAN, INFANTRY, "Central African Warrior", 0, 0, 1, 1, 2, 2)
  case object NORTH_AMERICAN_HUSSAR extends MilitaryUnit(14, NORTH_AMERICAN, CAVALRY, "North American Hussar", 1, 1, 3, 2, 3, 2)
  case object NORTH_AMERICAN_RIFLE_CAVALRY extends MilitaryUnit(10, NORTH_AMERICAN, CAVALRY, "North American Cavalry", 0, 1, 3, 2, 2, 2)
  case object OPEN_ORDER_CAVALRY extends MilitaryUnit(28, WESTERN, CAVALRY, "Latin Chasseur", 2, 1, 4, 4, 5, 5)
  case object OTTOMAN_AZAB extends MilitaryUnit(5, OTTOMAN, INFANTRY, "Azab Infantry", 0, 0, 1, 1, 2, 1)
  case object OTTOMAN_JANISSARY extends MilitaryUnit(9, OTTOMAN, INFANTRY, "Janissary Infantry", 1, 0, 1, 1, 2, 2)
  case object OTTOMAN_LANCER extends MilitaryUnit(28, OTTOMAN, CAVALRY, "Reformed Lancer", 1, 1, 5, 3, 5, 3)
  case object OTTOMAN_MUSELLEM extends MilitaryUnit(1, OTTOMAN, CAVALRY, "Musellem Cavalry", 0, 0, 2, 1, 1, 1)
  case object OTTOMAN_NEW_MODEL extends MilitaryUnit(30, OTTOMAN, INFANTRY, "Eastern New Model Infantry", 3, 3, 3, 3, 4, 4)
  case object OTTOMAN_NIZAMI_CEDID extends MilitaryUnit(23, OTTOMAN, INFANTRY, "Nizami Cedid Infantry", 2, 3, 2, 2, 3, 3)
  case object OTTOMAN_REFORMED_JANISSARY extends MilitaryUnit(19, OTTOMAN, INFANTRY, "Reformed Janissary Infantry", 2, 2, 2, 2, 3, 2)
  case object OTTOMAN_REFORMED_SPAHI extends MilitaryUnit(18, OTTOMAN, CAVALRY, "Reformed Spahi Cavalry", 1, 1, 3, 3, 3, 3)
  case object OTTOMAN_SEKBAN extends MilitaryUnit(12, OTTOMAN, INFANTRY, "Sekban Infantry", 2, 2, 2, 1, 2, 3)
  case object OTTOMAN_SPAHI extends MilitaryUnit(10, OTTOMAN, CAVALRY, "Spahi Cavalry", 0, 0, 3, 2, 3, 2)
  case object OTTOMAN_TIMARIOT extends MilitaryUnit(6, OTTOMAN, CAVALRY, "Timariot Cavalry", 0, 0, 2, 1, 2, 1)
  case object OTTOMAN_TOPRAKLI_DRAGOON extends MilitaryUnit(28, OTTOMAN, CAVALRY, "Toprakli Dragoons", 2, 2, 3, 3, 4, 4)
  case object OTTOMAN_TOPRAKLI_HIT_AND_RUN extends MilitaryUnit(23, OTTOMAN, CAVALRY, "Toprakli Hit and Run Cavalry", 2, 0, 4, 3, 4, 3)
  case object OTTOMAN_YAYA extends MilitaryUnit(1, OTTOMAN, INFANTRY, "Yaya Infantry", 0, 0, 1, 0, 1, 1)
  case object PEDRERO extends MilitaryUnit(10, WESTERN, ARTILLERY, "Pedrero", 1, 1, 0, 0, 1, 1)
  case object PERSIAN_CAVALRY_CHARGE extends MilitaryUnit(1, MUSLIM, CAVALRY, "Muslim Cavalry", 0, 0, 1, 0, 2, 1)
  case object PERSIAN_FOOTSOLDIER extends MilitaryUnit(1, MUSLIM, INFANTRY, "Muslim Foot Soldier", 0, 0, 1, 0, 1, 1)
  case object PERSIAN_RIFLE extends MilitaryUnit(30, MUSLIM, INFANTRY, "Muslim Rifle Infantry", 3, 3, 3, 3, 4, 4)
  case object PERSIAN_SHAMSHIR extends MilitaryUnit(9, MUSLIM, INFANTRY, "Shamshir Infantry", 0, 0, 2, 1, 2, 2)
  case object PERUVIAN_GUERILLA_WARFARE extends MilitaryUnit(19, SOUTH_AMERICAN, INFANTRY, "South American Guerrilla", 2, 2, 2, 2, 3, 3)
  case object POLISH_HUSSAR extends MilitaryUnit(14, EASTERN, CAVALRY, "Reformed Eastern Hussars", 1, 1, 3, 3, 2, 2)
  case object POLISH_MUSKETEER extends MilitaryUnit(12, EASTERN, INFANTRY, "Defensive Eastern Musketeers", 2, 2, 1, 2, 2, 2)
  case object POLISH_TERCIO extends MilitaryUnit(15, EASTERN, INFANTRY, "Eastern Tercio", 2, 2, 1, 2, 2, 3)
  case object POLISH_WINGED_HUSSAR extends MilitaryUnit(22, EASTERN, CAVALRY, "Winged Hussars", 0, 1, 5, 4, 4, 3)
  case object PRUSSIAN_DRILL extends MilitaryUnit(30, WESTERN, INFANTRY, "Drill Infantry", 4, 4, 3, 3, 4, 4)
  case object PRUSSIAN_FREDERICKIAN extends MilitaryUnit(26, WESTERN, INFANTRY, "Frederickian Infantry", 4, 3, 3, 3, 4, 3)
  case object PRUSSIAN_UHLAN extends MilitaryUnit(26, WESTERN, CAVALRY, "Uhlan Cavalry", 1, 2, 5, 4, 4, 3)
  case object PUEBLO_AMBUSH extends MilitaryUnit(5, NORTH_AMERICAN, INFANTRY, "Ambush Infantry", 0, 0, 1, 2, 2, 1)
  case object QIZILBASH_CAVALRY extends MilitaryUnit(10, MUSLIM, CAVALRY, "Qizilbash Cavalry", 0, 0, 2, 2, 3, 2)
  case object RAJPUT_HILL_FIGHTERS extends MilitaryUnit(1, INDIAN, CAVALRY, "Indian Cavalry", 0, 0, 0, 1, 1, 1)
  case object RAJPUT_MUSKETEER extends MilitaryUnit(12, INDIAN, INFANTRY, "Akbarid Musketeers", 2, 2, 1, 2, 2, 2)
  case object REFORMED_ASIAN_CAVALRY extends MilitaryUnit(28, CHINESE, CAVALRY, "Reformed Asian Cavalry", 1, 2, 5, 4, 3, 4)
  case object REFORMED_ASIAN_MUSKETEER extends MilitaryUnit(26, CHINESE, INFANTRY, "Reformed Asian Musketeer", 4, 4, 3, 3, 3, 3)
  case object REFORMED_MANCHU_RIFLE extends MilitaryUnit(28, CHINESE, CAVALRY, "Green Standard Cavalry", 2, 1, 4, 4, 4, 4)
  case object REFORMED_MUGHAL_MANSABDAR extends MilitaryUnit(14, INDIAN, CAVALRY, "Dai-Phat Cavalry", 2, 0, 2, 3, 3, 2)
  case object REFORMED_MUGHAL_MUSKETEER extends MilitaryUnit(12, INDIAN, INFANTRY, "South Indian Infantry", 2, 1, 2, 1, 3, 2)
  case object REFORMED_STEPPE_RIFLES extends MilitaryUnit(30, NOMAD, INFANTRY, "Reformed Steppe Rifles", 3, 3, 3, 3, 4, 4)
  case object REFORMED_WESTERNIZED_INCAN extends MilitaryUnit(30, SOUTH_AMERICAN, INFANTRY, "Reformed Westernized Incan Infantry", 4, 4, 3, 3, 3, 3)
  case object ROYAL_MORTAR extends MilitaryUnit(25, WESTERN, ARTILLERY, "Royal Mortar", 4, 4, 1, 1, 3, 3)
  case object RUSSIAN_COSSACK extends MilitaryUnit(28, EASTERN, CAVALRY, "Advanced Cossack Cavalry", 2, 1, 4, 4, 5, 4)
  case object RUSSIAN_CUIRASSIER extends MilitaryUnit(28, EASTERN, CAVALRY, "Eastern Cuirassiers", 1, 2, 5, 4, 4, 4)
  case object RUSSIAN_GREEN_COAT extends MilitaryUnit(26, EASTERN, INFANTRY, "Green Coat Infantry", 3, 3, 3, 3, 4, 4)
  case object RUSSIAN_LANCER extends MilitaryUnit(26, EASTERN, CAVALRY, "Lancers", 0, 1, 5, 4, 4, 4)
  case object RUSSIAN_MASS extends MilitaryUnit(30, EASTERN, INFANTRY, "Mass Infantry", 4, 3, 4, 3, 4, 3)
  case object RUSSIAN_PETRINE extends MilitaryUnit(23, EASTERN, INFANTRY, "Petrine Infantry", 2, 3, 2, 3, 3, 3)
  case object SAXON_INFANTRY extends MilitaryUnit(19, EASTERN, INFANTRY, "Saxon Infantry", 3, 2, 3, 2, 2, 2)
  case object SCHWARZE_REITER extends MilitaryUnit(10, WESTERN, CAVALRY, "Schwarze Reiter", 1, 0, 2, 1, 2, 2)
  case object SCOTTISH_HIGHLANDER extends MilitaryUnit(19, WESTERN, INFANTRY, "Highlanders Infantry", 2, 2, 3, 2, 4, 2)
  case object SHAYBANI extends MilitaryUnit(6, MUSLIM, CAVALRY, "Shaybanid Cavalry", 0, 0, 2, 1, 1, 2)
  case object SIKH_HIT_AND_RUN extends MilitaryUnit(18, INDIAN, INFANTRY, "North Indian Musket Infantry", 3, 2, 2, 2, 3, 2)
  case object SIKH_RIFLE extends MilitaryUnit(28, INDIAN, CAVALRY, "Mysorean Light Cavalry", 2, 1, 4, 4, 3, 4)
  case object SIOUX_DRAGOON extends MilitaryUnit(23, NORTH_AMERICAN, CAVALRY, "North American Dragoon", 2, 2, 3, 3, 4, 4)
  case object SLAVIC_STRADIOTI extends MilitaryUnit(6, EASTERN, CAVALRY, "Stratioti Cavalry", 0, 0, 2, 1, 1, 1)
  case object SMALL_CAST_IRON_BOMBARD extends MilitaryUnit(13, WESTERN, ARTILLERY, "Small Cast Iron Cannon", 1, 1, 0, 1, 2, 1)
  case object SONGHAI_TRIBAL_WARFARE extends MilitaryUnit(5, SUB_SAHARAN, INFANTRY, "West African Warrior", 0, 0, 1, 2, 1, 2)
  case object SOUTH_AMERICAN_ARQUEBUSIER extends MilitaryUnit(10, SOUTH_AMERICAN, INFANTRY, "South American Arquebusier", 1, 2, 1, 1, 2, 1)
  case object SOUTH_AMERICAN_DRAGOON extends MilitaryUnit(23, SOUTH_AMERICAN, CAVALRY, "South American Dragoon", 2, 2, 3, 3, 4, 4)
  case object SOUTH_AMERICAN_FOREST_WARFARE extends MilitaryUnit(5, SOUTH_AMERICAN, INFANTRY, "South American Forest Warriors", 0, 0, 1, 2, 2, 1)
  case object SOUTH_AMERICAN_GUNPOWDER_WARFARE extends MilitaryUnit(10, SOUTH_AMERICAN, INFANTRY, "Defensive American Musketeers", 1, 1, 1, 2, 1, 2)
  case object SOUTH_AMERICAN_HORSEMEN extends MilitaryUnit(6, SOUTH_AMERICAN, CAVALRY, "South American Horsemen", 0, 0, 2, 1, 1, 1)
  case object SOUTH_AMERICAN_HUSSAR extends MilitaryUnit(14, SOUTH_AMERICAN, CAVALRY, "South American Hussar", 1, 1, 3, 2, 3, 2)
  case object SOUTH_AMERICAN_REFORMED_GUNPOWDER_WARFARE extends MilitaryUnit(14, SOUTH_AMERICAN, INFANTRY, "Reformed American Musketeers", 2, 2, 2, 2, 2, 2)
  case object SOUTH_AMERICAN_RIFLE_CAVALRY extends MilitaryUnit(10, SOUTH_AMERICAN, CAVALRY, "South American Cavalry", 0, 1, 3, 2, 2, 2)
  case object SOUTH_AMERICAN_SPEARMEN extends MilitaryUnit(1, SOUTH_AMERICAN, INFANTRY, "South American Spearmen", 0, 0, 1, 1, 1, 0)
  case object SOUTH_AMERICAN_SWARM extends MilitaryUnit(19, SOUTH_AMERICAN, CAVALRY, "South American Swarm Cavalry", 1, 2, 3, 3, 3, 2)
  case object SOUTH_AMERICAN_WARFARE extends MilitaryUnit(1, SOUTH_AMERICAN, INFANTRY, "American Mountain Warriors", 0, 0, 0, 1, 1, 1)
  case object SOUTH_INDIAN_MUSKETEER extends MilitaryUnit(9, INDIAN, INFANTRY, "Poligar Infantry", 1, 2, 1, 1, 1, 1)
  case object SPANISH_TERCIO extends MilitaryUnit(12, WESTERN, INFANTRY, "Tercio Infantry", 1, 2, 1, 2, 2, 2)
  case object STEPPE_CAVALRY extends MilitaryUnit(23, NOMAD, CAVALRY, "Steppe Cavalry", 1, 1, 4, 3, 3, 3)
  case object STEPPE_FOOTMEN extends MilitaryUnit(12, NOMAD, INFANTRY, "Steppe Footmen", 1, 1, 2, 2, 2, 2)
  case object STEPPE_INFANTRY extends MilitaryUnit(19, NOMAD, INFANTRY, "Steppe Infantry", 2, 2, 3, 3, 3, 2)
  case object STEPPE_LANCERS extends MilitaryUnit(14, NOMAD, CAVALRY, "Steppe Lancers", 0, 0, 3, 3, 3, 3)
  case object STEPPE_MOUNTED_RAIDERS extends MilitaryUnit(18, NOMAD, CAVALRY, "Mounted Steppe Raiders", 0, 1, 3, 3, 3, 3)
  case object STEPPE_MUSKETEERS extends MilitaryUnit(15, NOMAD, INFANTRY, "Steppe Musketeers", 2, 1, 3, 2, 2, 2)
  case object STEPPE_RAIDERS extends MilitaryUnit(9, NOMAD, INFANTRY, "Steppe Raiders", 0, 0, 2, 1, 1, 2)
  case object STEPPE_RIDERS extends MilitaryUnit(10, NOMAD, CAVALRY, "Steppe Riders", 0, 0, 3, 2, 3, 2)
  case object STEPPE_RIFLES extends MilitaryUnit(26, NOMAD, INFANTRY, "Steppe Rifles", 2, 3, 3, 3, 4, 4)
  case object STEPPE_UHLANS extends MilitaryUnit(28, NOMAD, CAVALRY, "Steppe Uhlans", 1, 1, 5, 4, 4, 3)
  case object SWEDISH_ARME_BLANCHE extends MilitaryUnit(23, WESTERN, CAVALRY, "Arme Blanche Cavalry", 1, 1, 5, 3, 5, 3)
  case object SWEDISH_CAROLINE extends MilitaryUnit(23, WESTERN, INFANTRY, "Caroline Infantry", 3, 2, 3, 2, 3, 3)
  case object SWEDISH_GALLOP extends MilitaryUnit(18, WESTERN, CAVALRY, "Gallop Cavalry", 1, 1, 4, 3, 3, 3)
  case object SWEDISH_GUSTAVIAN extends MilitaryUnit(19, WESTERN, INFANTRY, "Gustavian Infantry", 3, 2, 3, 2, 3, 2)
  case object SWISS_LANDSKNECHTEN extends MilitaryUnit(9, WESTERN, INFANTRY, "Landsknechten Infantry", 0, 0, 1, 1, 1, 2)
  case object SWIVEL_CANNON extends MilitaryUnit(20, WESTERN, ARTILLERY, "Swivel Cannon", 3, 2, 1, 1, 3, 2)
  case object TARTAR_COSSACK extends MilitaryUnit(26, EASTERN, CAVALRY, "Reformed Cossack Cavalry", 1, 1, 4, 4, 4, 4)
  case object TIPU_SULTAN_ROCKET extends MilitaryUnit(30, INDIAN, INFANTRY, "Indian Drill Infantry", 4, 3, 3, 3, 4, 3)
  case object TOFONGCHIS_MUSKETEER extends MilitaryUnit(12, MUSLIM, INFANTRY, "Muslim Musketeer", 2, 1, 1, 2, 2, 3)
  case object TOPCHIS_ARTILLERY extends MilitaryUnit(14, MUSLIM, CAVALRY, "Muslim Musketeer Cavalry", 1, 0, 2, 2, 3, 2)
  case object WESTERN_LONGBOW extends MilitaryUnit(5, WESTERN, INFANTRY, "Longbow", 0, 0, 1, 0, 1, 1)
  case object WESTERN_MEDIEVAL_INFANTRY extends MilitaryUnit(1, WESTERN, INFANTRY, "Latin Medieval Infantry", 0, 0, 0, 0, 1, 1)
  case object WESTERN_MEDIEVAL_KNIGHTS extends MilitaryUnit(1, WESTERN, CAVALRY, "Latin Knights", 0, 0, 1, 0, 1, 1)
  case object WESTERN_MEN_AT_ARMS extends MilitaryUnit(5, WESTERN, INFANTRY, "Men at Arms", 0, 0, 0, 1, 1, 1)
  case object WESTERNIZED_ADAL extends MilitaryUnit(26, SUB_SAHARAN, INFANTRY, "Westernized East African Infantry", 4, 4, 2, 2, 3, 4)
  case object WESTERNIZED_AZTEC extends MilitaryUnit(26, MESOAMERICAN, INFANTRY, "Westernized American Hill Infantry", 3, 4, 2, 3, 3, 4)
  case object WESTERNIZED_BANTU extends MilitaryUnit(26, SUB_SAHARAN, INFANTRY, "Westernized South African Infantry", 4, 3, 3, 3, 3, 3)
  case object WESTERNIZED_ETHIOPIAN extends MilitaryUnit(26, SUB_SAHARAN, INFANTRY, "Westernized North African Infantry", 3, 4, 2, 4, 3, 3)
  case object WESTERNIZED_INCAN extends MilitaryUnit(26, SOUTH_AMERICAN, INFANTRY, "Westernized Incan Infantry", 4, 3, 3, 3, 3, 3)
  case object WESTERNIZED_MAYAN extends MilitaryUnit(30, MESOAMERICAN, INFANTRY, "Westernized Central American infantry", 4, 3, 3, 3, 3, 4)
  case object WESTERNIZED_NIGER_KONGOLESE extends MilitaryUnit(26, SUB_SAHARAN, INFANTRY, "Westernized Central African Infantry", 3, 3, 3, 3, 4, 3)
  case object WESTERNIZED_SOUTH_AMERICAN extends MilitaryUnit(26, SOUTH_AMERICAN, INFANTRY, "Westernized South American Infantry", 3, 4, 2, 3, 3, 4)
  case object WESTERNIZED_ZAPOTEC extends MilitaryUnit(26, MESOAMERICAN, INFANTRY, "Westernized American Plains Infantry", 4, 3, 4, 3, 3, 2)
  case object ZAPOROGHIAN_COSSACK extends MilitaryUnit(14, EASTERN, CAVALRY, "Southern Cossacks", 0, 1, 4, 2, 2, 3)
  case object ZAPOTEC_GUNPOWDER_WARFARE extends MilitaryUnit(14, MESOAMERICAN, INFANTRY, "Offensive American Musketeers", 2, 1, 1, 2, 3, 3)
  case object ZAPOTEC_PLAINS_WARFARE extends MilitaryUnit(10, MESOAMERICAN, INFANTRY, "Reformed American Plains Warriors", 0, 0, 1, 2, 3, 2)
  case object ZAPOTEC_TRIBAL_WARFARE extends MilitaryUnit(5, MESOAMERICAN, INFANTRY, "American Plains Warriors", 0, 0, 1, 1, 2, 2)
}